# CASE FOLDING

In [1]:
# 1.1 Import Library
import pandas as pd
import os

In [2]:
# 1.2 Load Dataset Hasil Data Cleaning
df = pd.read_csv('datacleaning/data_cleaning_final.csv')

print("Dataset berhasil dimuat.")
print("Jumlah data:", len(df))

df.head()

Dataset berhasil dimuat.
Jumlah data: 13192

,no,timestamp,teks
0,1,2016-12-30T06:37:56.000Z,ADIL loh utk yg punya kebijakan publik negara ...
1,2,2016-12-30T06:30:36.000Z,Tertibkan Media Online DPR Pemerintah Jangan S...
2,3,2016-12-30T04:48:35.000Z,harus dievaluasi lg kebijakan bebas visa truta...
3,4,2016-12-30T04:21:40.000Z,jangan ngambang aturan logis apa undang undang
4,5,2016-12-30T02:36:13.000Z,Kebebasan bersuara berpendapat memang dijamin ...

In [3]:
# 1.3 Proses Case Folding (Mengubah seluruh teks menjadi huruf kecil)

df['teks_casefold'] = df['teks'].str.lower()

print("Case folding selesai.")
df[['teks', 'teks_casefold']].head()

Case folding selesai.

,teks,teks_casefold
0,ADIL loh utk yg punya kebijakan publik negara ...,adil loh utk yg punya kebijakan publik negara ...
1,Tertibkan Media Online DPR Pemerintah Jangan S...,tertibkan media online dpr pemerintah jangan s...
2,harus dievaluasi lg kebijakan bebas visa truta...,harus dievaluasi lg kebijakan bebas visa truta...
3,jangan ngambang aturan logis apa undang undang,jangan ngambang aturan logis apa undang undang
4,Kebebasan bersuara berpendapat memang dijamin ...,kebebasan bersuara berpendapat memang dijamin ...

In [4]:
# 1.4 Simpan Checkpoint Setelah Case Folding

output_path = 'datapreprocessing'
os.makedirs(output_path, exist_ok=True)

df.to_csv(
    os.path.join(output_path, 'data_after_casefolding.csv'),
    index=False
)

print("data_after_casefolding.csv berhasil disimpan.")

data_after_casefolding.csv berhasil disimpan.

# TOKENIZATION

In [5]:
import sys
!{sys.executable} -m ensurepip --upgrade
!{sys.executable} -m pip install nltk

Looking in links: c:\Users\ASUS\AppData\Local\Temp\tmp5tzc2mn3
Requirement already satisfied: setuptools in d:\ta\proyekscraping\lib\site-packages (65.5.0)
Requirement already satisfied: pip in d:\ta\proyekscraping\lib\site-packages (24.0)
Requirement already satisfied: nltk in d:\ta\proyekscraping\lib\site-packages (3.9.3)
Requirement already satisfied: click in d:\ta\proyekscraping\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in d:\ta\proyekscraping\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in d:\ta\proyekscraping\lib\site-packages (from nltk) (2026.2.19)
Requirement already satisfied: tqdm in d:\ta\proyekscraping\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in c:\users\asus\appdata\roaming\python\python311\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
# 2.1 Import Library Tokenization
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [7]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [8]:
# 2.2 Load Dataset Setelah Case Folding
df = pd.read_csv('datapreprocessing/data_after_casefolding.csv')

print("Dataset berhasil dimuat.")
print("Jumlah data:", len(df))

Dataset berhasil dimuat.
Jumlah data: 13192

In [9]:
# 2.3 Proses Tokenization
from nltk.tokenize import word_tokenize

df['teks_token'] = df['teks_casefold'].apply(word_tokenize)

print("Tokenization selesai.")
df[['teks_casefold', 'teks_token']].head()

Tokenization selesai.

,teks_casefold,teks_token
0,adil loh utk yg punya kebijakan publik negara ...,"[adil, loh, utk, yg, punya, kebijakan, publik,..."
1,tertibkan media online dpr pemerintah jangan s...,"[tertibkan, media, online, dpr, pemerintah, ja..."
2,harus dievaluasi lg kebijakan bebas visa truta...,"[harus, dievaluasi, lg, kebijakan, bebas, visa..."
3,jangan ngambang aturan logis apa undang undang,"[jangan, ngambang, aturan, logis, apa, undang,..."
4,kebebasan bersuara berpendapat memang dijamin ...,"[kebebasan, bersuara, berpendapat, memang, dij..."

In [10]:
# 2.4 Simpan Checkpoint Setelah Tokenization

df.to_csv(
    os.path.join('datapreprocessing', 'data_after_tokenization.csv'),
    index=False
)

print("data_after_tokenization.csv berhasil disimpan.")

data_after_tokenization.csv berhasil disimpan.

# Stopword Removal

In [11]:
# 3.1 Import Library Stopword
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

# Stopword bawaan NLTK Bahasa Indonesia
stop_words = set(stopwords.words('indonesian'))

# Tambahan stopword tidak baku 
additional_stopwords = {
    'yg', 'utk', 'tdk', 'lg', 'aja', 'dll', 
    'nya', 'nih', 'sih', 'dong', 'kok'
}

# Gabungkan stopword bawaan + tambahan
stop_words = stop_words.union(additional_stopwords)

print("Total stopwords:", len(stop_words))

Total stopwords: 766

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [12]:
# 3.2 Load Dataset Setelah Tokenization
df = pd.read_csv('datapreprocessing/data_after_tokenization.csv')

# Karena teks_token tersimpan sebagai string list, kita ubah kembali ke list
import ast
df['teks_token'] = df['teks_token'].apply(ast.literal_eval)

print("Dataset berhasil dimuat.")

Dataset berhasil dimuat.

In [13]:
# 3.3 Proses Stopword Removal

df['teks_stopword'] = df['teks_token'].apply(
    lambda tokens: [word for word in tokens if word not in stop_words]
)

print("Stopword removal selesai.")
df[['teks_token', 'teks_stopword']].head()

Stopword removal selesai.

,teks_token,teks_stopword
0,"[adil, loh, utk, yg, punya, kebijakan, publik,...","[adil, loh, kebijakan, publik, negara, !, !, !]"
1,"[tertibkan, media, online, dpr, pemerintah, ja...","[tertibkan, media, online, dpr, pemerintah, sp..."
2,"[harus, dievaluasi, lg, kebijakan, bebas, visa...","[dievaluasi, kebijakan, bebas, visa, trutama, ..."
3,"[jangan, ngambang, aturan, logis, apa, undang,...","[ngambang, aturan, logis, undang, undang]"
4,"[kebebasan, bersuara, berpendapat, memang, dij...","[kebebasan, bersuara, berpendapat, dijamin, uu..."

In [14]:
# 3.4 Simpan Checkpoint Setelah Stopword Removal

df.to_csv(
    os.path.join('datapreprocessing', 'data_after_stopword_removal.csv'),
    index=False
)

print("data_after_stopword_removal.csv berhasil disimpan.")

data_after_stopword_removal.csv berhasil disimpan.

# Stemming

In [15]:
# 4.1 Install dan Import Library Sastrawi 
import sys
!{sys.executable} -m pip install Sastrawi

Requirement already satisfied: Sastrawi in d:\ta\proyekscraping\lib\site-packages (1.0.1)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
# 4.2 Load Dataset Setelah Stopword Removal
df = pd.read_csv('datapreprocessing/data_after_stopword_removal.csv')

df['teks_stopword'] = df['teks_stopword'].apply(ast.literal_eval)

print("Dataset berhasil dimuat.")

Dataset berhasil dimuat.

In [17]:
# 4.3 Inisialisasi Stemmer
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
stemmer = factory.create_stemmer()

In [18]:
# 4.4 Proses Stemming

def stemming_process(tokens):
    return [stemmer.stem(word) for word in tokens]

df['teks_stemming'] = df['teks_stopword'].apply(stemming_process)

print("Stemming selesai.")
df[['teks_stopword', 'teks_stemming']].head()

Stemming selesai.

,teks_stopword,teks_stemming
0,"[adil, loh, kebijakan, publik, negara, !, !, !]","[adil, loh, bijak, publik, negara, , , ]"
1,"[tertibkan, media, online, dpr, pemerintah, sp...","[tertib, media, online, dpr, perintah, sporadi..."
2,"[dievaluasi, kebijakan, bebas, visa, trutama, ...","[evaluasi, bijak, bebas, visa, trutama, negara..."
3,"[ngambang, aturan, logis, undang, undang]","[ngambang, atur, logis, undang, undang]"
4,"[kebebasan, bersuara, berpendapat, dijamin, uu...","[bebas, suara, dapat, jamin, uu, bebas, bablas..."

In [19]:
# 4.5 Menggabungkan Kembali Token Menjadi Kalimat

df['teks_final'] = df['teks_stemming'].apply(lambda tokens: ' '.join(tokens))

df[['teks_stemming', 'teks_final']].head()

,teks_stemming,teks_final
0,"[adil, loh, bijak, publik, negara, , , ]",adil loh bijak publik negara
1,"[tertib, media, online, dpr, perintah, sporadi...",tertib media online dpr perintah sporadis sele...
2,"[evaluasi, bijak, bebas, visa, trutama, negara...",evaluasi bijak bebas visa trutama negara tiong...
3,"[ngambang, atur, logis, undang, undang]",ngambang atur logis undang undang
4,"[bebas, suara, dapat, jamin, uu, bebas, bablas...",bebas suara dapat jamin uu bebas bablas tabrak...

In [20]:
# 4.6 Simpan Dataset Hasil Preprocessing

df.to_csv(
    os.path.join('datapreprocessing', 'data_preprocessing_final.csv'),
    index=False
)

print("data_preprocessing_final.csv berhasil disimpan.")

data_preprocessing_final.csv berhasil disimpan.